### ISSUE TITLE
Configuration with private subnet as the default 

### ISSUE THREAD

**Issue by sunojram** [awsdocs/amazon-redshift-management-guide#13]
Per https://docs.aws.amazon.com/redshift/latest/mgmt/getting-started-cluster-in-vpc.html it is suggested to use a publicy accessible cluster. However, this is not a secure default since there are many threats with exposing services publicly and instead we must suggest using a private subnet. 

Thanks

**Comment by keithhc2** [comment]
@sunojram I did a quick search for "publicly accessible" in the page you listed, and I couldn't find any results, so I believe we addressed the issue here. If you believe that the issue still exists, feel free to provide feedback using the Provide feedback link at the bottom of [the page](https://docs.aws.amazon.com/redshift/latest/mgmt/getting-started-cluster-in-vpc.html).
